### ISSUE TITLE
Can it support launching from other work path?

### ISSUE THREAD

**Issue by hyee** [mauropagano/sqld360#1]
Hi,
Since sqld360 only supports executing from the path where sqld360.sql is, sometimes the process need to be aborted, or missing the "zip" command in OS level, thus would leave some temp files. 

What I expect is sqld360 to support lauching from other path, and then I can manually copy the "js" folder into that path to make sure the result pages are all fine.
Thank you

**Comment by mauropagano** [comment]
Hi Hyee,

I'm not sure I understand what you are asking. 
What is the exact problem of having to lunch the script for the folder it's included in? That's actually the whole idea :-) 
Can you show me a real example of what you are suggesting?

I understand missing the zip files or aborting the execution will leave temporary files but I believe cleaning those "dirty" files would be cleaner and easier than having to manually move a folder each time just to make sure the reports work (they would anyway, there is not that much into the js/).

Thanks,
Mauro

**Comment by hyee** [comment]
Supposing sqld360 locates at c:\sqld360, and my working folder is c:\temp.
Then I start sqlplus, and run @c:\sqld360\sqld360.sql, it shows that some sql files are missing.
For above scenario, my expectation is at least the file missing issue should not exist. Thanks

**Comment by mauropagano** [comment]
Thanks for the explanation, that's actually the expected behavior.
sqld360.sql isn't a standalone script and as such "it depends" the rest of
the scripts (/sql) to be in a specific location, invoking it from another
location breaks it and that's normal.
This is also how several other tools work (i.e. eDB360 and SQLTXPLAIN just
to mention a couple).

Being SQLd360 so small you could probably move it (or copy it) into the
temporary folder.

**Comment by hyee** [comment]
You are right, thank you

**Comment by xtender** [comment]
Hi Mauro!

btw, you can get current directory of your main script for later usage very easy: I've pushed simple example -
https://github.com/xtender/xt_scripts/blob/master/inc/curr_path.sql

Best regards,
Sayan Malakshinov
http://orasql.org

**Comment by mauropagano** [comment]
Thanks Sayan! 
I usually do something like the following to get my pwd but I sure like your script too!!

host echo def pwd=`pwd` > current_pwd.sql
@current_pwd
host rm current_pwd.sql
prompt &pwd

I'm also pretty sure I'll find a lot of other interesting things in your GitHub scripts :-)

**Comment by xtender** [comment]
Mauro, 
unfortunately "host pwd" will show only directory where sqlplus was started, so if i have file "test/pwd.sql"  with "host pwd" and i will execute it @test/pwd, it will show start directory only.

**Comment by xtender** [comment]
But if you will execute my script @path/to/this/curr_path 
it will return "path/to/this"

**Comment by mauropagano** [comment]
You are right and I didn't understood that was the requirement :-(
Now I see what you mean!

Thanks,
Mauro

**Comment by xtender** [comment]
I'm glad I was able to help! 
So we can hope that sqld360 will spool temp files and results to own directory? :)

**Comment by mauropagano** [comment]
Not shortly :-)
I didn't realize it was such a problem (this is the first time anybody
mentions it to me and several other tools I worked on have the same
behavior) but I will sure add it to the list of enhancements!

**Comment by xtender** [comment]
Of course, this is not a problem :) especially if many people start SQL*Plus for SQLD360 only - unfortunately too many developers and DBA's use GUI tools :(
BTW, I like and always use the Tanel's approach: the using special variables for SPOOL and temp files
