### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by dalfa** [mauropagano/sqld360#2]
Ciao Mauro,

It's not really an issue, anyway..  I'm trying sqld360 on a windows installation, obviously it cannot find env, cat, etc.
`
1a. Database Configuration
<ol start="1">
'rm' is not recognized as an internal or external command,
operable program or batch file.

'cat' is not recognized as an internal or external command,
operable program or batch file.

'lsconf' is not recognized as an internal or external command,
operable program or batch file.

'psrinfo' is not recognized as an internal or external command,
operable program or batch file.

SP2-0223: No lines in SQL buffer.

'rm' is not recognized as an internal or external command,
operable program or batch file.
`

regards,
Fabrizio

**Comment by mauropagano** [comment]
Ciao Fabrizio,

those errors are safe to ignore.
You can use the Unix utils (or any variations of it) to provide most of the *nix utilities used by SQLd360 but really just zip is necessary, everything else isn't really necessary

Cheers,
Mauro
