### ISSUE TITLE
Too many binds

### ISSUE THREAD

**Issue by dalfa** [mauropagano/sqld360#3]
Ciao Mauro,

I'm running sqld360 on a win2012r2 machine with a 12cR1 db, it fails to get bind variables:
`14:12:36 col:2of5 "00086_sqld360_147264_0juzvshqdu9b7_2g_50_binds_list_from_memory.html"
Error 45 initializing SQL*Plus
Internal error`
perhaps there are too many binds.

regards,
Fabrizio

**Comment by mauropagano** [comment]
Ciao Fabrizio,
 
Any chance you can send me this file plus the rest of the zip generated so far via email (address on my blog)?
I'm asking because this doesn't look like a SQLd360 problem but I wanted to make sure

Thanks,
Mauro

**Comment by mauropagano** [comment]
SQL*Plus problem, not much too fix from SQLd360 (working with Fabrizio via email)
